import { ClerkProvider } from '@clerk/nextjs'
import RootStyleRegistry from './emotion'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <RootStyleRegistry>{children}</RootStyleRegistry>
        </body>
      </html>
    </ClerkProvider>
  )
}
